### ISSUE TITLE
Tomcat Server configuration is not working

### ISSUE THREAD

**Issue by RobertoDebarba** [zengkid/SmartTomcat#1]
Hey!

On Intellij Community 2017.1, when I try to configure a Tomcat Server on SmartTomcat configurations, I selected a tomcat instalation directory, the item does not appear on list, but the button to remove is enabled, as if it were active. The name, version and server does not appear too.
I am unable to configure the plugin.
Plugin version: 1.6

![image](https://user-images.githubusercontent.com/5933968/26929063-b91d4224-4c2e-11e7-9ef9-d947ad193639.png)

Thanks for your help. This plugin is indispensable for community edition.

**Comment by zengkid** [comment]
Hi, RobertoDebarba

  Please config the JDK for your project.

**Comment by RobertoDebarba** [comment]
It's already configured.

![capturar2](https://user-images.githubusercontent.com/5933968/27034339-a1202a60-4f53-11e7-81f1-ed2196c7d416.PNG)
![capturar3](https://user-images.githubusercontent.com/5933968/27034338-a11bd4e2-4f53-11e7-8dfa-c6b4dd86d9ee.PNG)
![capturar1](https://user-images.githubusercontent.com/5933968/27034340-a1418fde-4f53-11e7-8d87-c6f3d94dffaa.PNG)
