### ISSUE TITLE
Running main class triggers SmartTomcat configuration

### ISSUE THREAD

**Issue by jans9000** [zengkid/SmartTomcat#100]
**Describe the bug**

When trying to run a java main class, the SmartTomcat run configuration is triggered.

Steps:
- create a war project, e.g. from maven-archetype-webapp
- add a java class with a main method
- try to run the class by right-mouse click on green icon
- smart tomcat run configuration kicks in

Workaround: use more Run/Debug

**Screenshots**

![image](https://user-images.githubusercontent.com/118439077/202429631-535dd86a-e7f5-49ec-bf25-dc2606cc7d1a.png)

**Intellij & SmartTomcat Version (Help -> About copy & paste below)**

IntelliJ IDEA 2022.2.3 (Ultimate Edition)
Build #IU-222.4345.14, built on October 5, 2022
Runtime version: 17.0.4.1+7-b469.62 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-53-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 16384M
Cores: 8
Non-Bundled Plugins:
    com.poratu.idea.plugins.tomcat (4.3.7)
    String Manipulation (9.6.1)
    EclipseCodeFormatter (22.0.203.000.0-Eclipse_2021-09)
    com.intellij.properties.bundle.editor (222.4345.14)
    com.jetbrains.writerside (2022.09.2767)
    Dart (222.4345.14)
    intellij.prettierJS (222.4345.14)
    com.jetbrains.lang.ejs (222.4345.14)
    Pythonid (222.4345.14)

Kotlin: 222-1.7.10-release-334-IJ4345.14
Current Desktop: ubuntu:GNOME

**Comment by yuezk** [comment]
Thanks for your feedback, will looking into this.

**Comment by yuezk** [comment]
Fixed in 4.3.8.

**Comment by jans9000** [comment]
Thanks a lot, great plugin btw !
