### ISSUE TITLE
.SmartTomcat/.../conf/web.xml formatting issue

### ISSUE THREAD

**Issue by MikeC1419** [zengkid/SmartTomcat#106]
The web.xml file has spaces in the first line before ' ?xml version="1.0" encoding="UTF-8"?' every time the server is started from IntelliJ.

As a result my server does not work until I manually edit the file to delete the spaces one the first line before '?xml version="1.0" encoding="UTF-8"?'

Intellij version 2023 1.2
SmartTomcat Version 4.5.0
Apache Tomcat 10.0.2
(note this issue did not occur when I switched to Tomcat 9.0.75)

**Comment by tb12315** [comment]
你发的邮件我已经收到。会在近期内查看。

**Comment by yuezk** [comment]
@MikeC1419 SmartTomcat just copies the web.xml, but it never changes its content, I'm afraid this issue is not related to SmartTomcat.

**Comment by AlvinZyhalj** [comment]
Where does the SmartTomcat just copy the web.xml from? I changed my C:\works\apps\apache-tomcat-9.0.64\conf\web.xml file to add some filter definitions, but it always can use an old one.

![image](https://github.com/user-attachments/assets/06c4110e-2f55-412a-9e41-2660883e61cc)

**Comment by tb12315** [comment]
你发的邮件我已经收到。会在近期内查看。
