### ISSUE TITLE
SSL & java.lang.NullPointerException: Cannot invoke "org.w3c.dom.Element.setAttribute(String, String)" because "portE" is null

### ISSUE THREAD

**Issue by sgorbenko** [zengkid/SmartTomcat#114]
When running IntelliJ SmartTomcat, I get this error:

java.lang.NullPointerException: Cannot invoke "org.w3c.dom.Element.setAttribute(String, String)" because "portE" is null

I believe it is due to the fact that I have SSL enabled in server.config:
![image](https://github.com/zengkid/SmartTomcat/assets/23386465/f50aea4d-54e0-403a-9eb5-32916814300e)

IntelliJ IDEA 2023.2.1 (Community Edition)
Build #IC-232.9559.62, built on August 23, 2023
Runtime version: 17.0.8+7-b1000.8 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4086M
Cores: 16
Registry:
    ide.experimental.ui=true

Non-Bundled Plugins:
    com.poratu.idea.plugins.tomcat (4.7.0)

**Comment by yuezk** [comment]
You could keep the non-SSL configuration even though the SSL is enabled.

**Comment by OnelSarmiento** [comment]
Is there any workaround for this?

**Comment by yuezk** [comment]
Fixed in #119
