### ISSUE TITLE
Custom context.xml

### ISSUE THREAD

**Issue by Isukthar** [zengkid/SmartTomcat#116]
Hello,
I installed SmartTomcat plugin, but I don't find how I can customize Tomcat files for the instance I create with the plugin.
I'd like to modify context.xml file, without changing it in tomcat binaries folder.
Is there a way to do it or it's a new feature request ?

Thx

**Comment by yuezk** [comment]
@Isukthar You can add a custom context by following https://github.com/zengkid/SmartTomcat#:~:text=to%20deployment%20directory.-,Custom%20Context,-opional%2C%20if. If that is not your need, then I'm afraid it could be a feature request.

**Comment by Isukthar** [comment]
My problem is that the feature in your link use a context.xml embedded in the application.
Usually, with a dedicated tomcat, we use a separate context.xml copied in tomcat config.
So yes, feature request.

**Comment by yuezk** [comment]
Currently, the context.xml for SmartTomcat is copied from the location of the Tomcat you selected. But you need a way to modify or specify the context.xml for SmartTomcat. Right?

**Comment by Isukthar** [comment]
Yes, i need to make per application changes on context.xml, without modifying original context.xml.

thx
