### ISSUE TITLE
can't input Tomcat name and version in Settings with IDEA community version 2018.1.3 on Win10

### ISSUE THREAD

**Issue by HowieChih** [zengkid/SmartTomcat#12]
## Dev Environment
- IntelliJ IDEA 2018.1.3 (Community Edition)
- Build #IC-181.4892.42, built on May 8, 2018
- JRE: 1.8.0_152-release-1136-b38 amd64
- JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
- Window 10.0.15063, 64 bit.

## Way of installation
the follow 2 ways have been tested both: 
- download Smart Tomcat 2.5 from [https://plugins.jetbrains.com/plugin/9492-smart-tomcat](https://plugins.jetbrains.com/plugin/9492-smart-tomcat), and install it from disk in IDEA.
- install from IDEA plugin repository

## Issue
Global Tomcat Configuration can't input Tomcat name and version in the Settings. The name in server list always shows "null" when a new Tomcat added. And the Settings Menu is also different from the [https://plugins.jetbrains.com/plugin/9492-smart-tomcat](https://plugins.jetbrains.com/plugin/9492-smart-tomcat) page shows.

A ``NullPointerException`` throws after running project with the server above named "null".

![image](https://user-images.githubusercontent.com/13414813/40114260-c4fb5f40-593e-11e8-9733-ba9c7d4534c6.png)

![image](https://user-images.githubusercontent.com/13414813/40114343-246b26f4-593f-11e8-96d7-19e18e9e954a.png)

Is there anything I can do to run the project successfully? Thanks.

**Comment by yl-coder** [comment]
@HowieChih could you try version 2.0 and see if it works?

**Comment by yl-coder** [comment]
the space between Program Files may cause an issue, i suspect.

**Comment by yl-coder** [comment]
I managed to reproduce the error on Mac OSX. It happens when there is space in the tomcat path.

**Comment by HowieChih** [comment]
Thanks for the help. After installing Tomcat into path without space, it works fine.

**Comment by leopintos11** [comment]
Hi guys. I'm having the same problem but my Tomcat path doesn't have any space.
![image](https://user-images.githubusercontent.com/29589984/47527348-b3dbc600-d878-11e8-9689-c417e0b5cea5.png)

**Comment by yl-coder** [comment]
@leopintos11 maybe intellij doesn't have permission to your C: directory. Try place your tomcat in Program files or your home directory

**Comment by leopintos11** [comment]
I have Tomcat 6 also in C drive and it's working fine. Anyway tryied your suggestion, not working. I think it's a plugin issue.

**Comment by zengkid** [comment]
Please remove and try again.

________________________________

**Comment by parthmakadiya12** [comment]
Still, the same problem exists on MacOS.(Mojave)

<img width="859" alt="Screenshot 2019-12-10 at 6 38 45 PM" src="https://user-images.githubusercontent.com/10697769/70553969-7de0ca80-1b7c-11ea-861e-45d4858149fe.png">

I don't have any space in my path.
I used brew to install the tomcat.
Any Help is appreciated.

**Comment by zengkid** [comment]
@parthmakadiya12 please try to upgrade the latest version 3.5.0
if still get error, please try to execute below cmd in MacOS see if have any issue

'''sh
cd ${tomcat_home}
 $[java_home}/bin/java -cp lib/catalina.jar org.apache.catalina.util.ServerInfo
'''

**Comment by zengkid** [comment]
move to issue #33

**Comment by athaisyah** [comment]
Hi i have almost the similiar issue on my laptop windows 10, with intellij 2020.2.3, can anyone please help. What does it mean by space in path. Im really new on this and couldnt find anyone with same problems

**Comment by zengkid** [comment]
@athaisyah Could you share your error log and screenshot?

**Comment by athaisyah** [comment]
The main problem I couldn't load tomcat apache in tomcat server configuration.
What I have done is uninstall in intellij and java jdk jre. and clean it.
then I begin from the first again to install java and intellij, have been doing this 2times.
My intelij version is 2020.2.3 (Community Edition), with java 8.
Anyone maybe could share other solution that I can try?
Thanks in advance!:)
![Capture](https://user-images.githubusercontent.com/57663851/96361599-56ba3880-1151-11eb-99dd-df63c15473b8.JPG)
![ezgif com-gif-maker](https://user-images.githubusercontent.com/57663851/96361601-5ae65600-1151-11eb-9683-38b2d6ea1d97.gif)

**Comment by zengkid** [comment]
@athaisyah  please try to click 'Configuration' and add tomcat server.

**Comment by athaisyah** [comment]
I have tried through tomcat server, however still couldn't load😔

**Comment by zengkid** [comment]
In server setting. added successfully or fail?

**Comment by nickmcsimpson** [comment]
I'm having the same issue trying to setup my Tomcat server with this plugin. I can choose the file location `Settings > Tomcat Server > +`
![image](https://user-images.githubusercontent.com/25393558/96786617-2a532600-13b6-11eb-9696-d0c900e50a8b.png)
But Name and Version are not populating as the others have shown, making this unusable. 

I downloaded the Core zip from [Tomcat website](https://tomcat.apache.org/download-90.cgi) and unzipped in this location. This is new to me as well, did I miss a step?

ASIDE: I can run `mvn tomcat:run` on my project and get my project to run, but I don't think it's configured appropriately. I wanted to use the full functionality of this plugin to make the server config more straight forward.

I've tried uninstalling the plugin, restarting the IDE and fiddling with folder location to no avail. Any help would be greatly appreciated.

**Comment by zengkid** [comment]
@nickmcsimpson have you got any error?
select path should be c:\JavaDev\apache-tomcat-9.0.39\apache-tomcat-9.0.39

**Comment by nickmcsimpson** [comment]
No error is thrown when trying to select the folder, but there is an error trying to start Tomcat if I attempt to use the no-name configuration. Doesn't matter if I select the sub folder, same behavior.

**Comment by zengkid** [comment]
after select tomcat folder, does add tomcat successfully ? Are tomcat name and tomcat version correct?
![image](https://user-images.githubusercontent.com/3382739/96941797-fd158d80-1505-11eb-98fc-cc99b51d08f1.png)

**Comment by nickmcsimpson** [comment]
No version or name appears and this is precisely the issue.

**Comment by zengkid** [comment]
@nickmcsimpson 
please try run below command in cmd:
cd c:\JavaDev\apache-tomcat-9.0.39\apache-tomcat-9.0.39
 $[java_home}/bin/java -cp lib/catalina.jar org.apache.catalina.util.ServerInfo

**Comment by nickmcsimpson** [comment]
@zengkid Do you have a Windows equivalent command?

**Comment by zengkid** [comment]
@nickmcsimpson 

window command, please make sure java is in your path.

cd c:\JavaDev\apache-tomcat-9.0.39\apache-tomcat-9.0.39
java -cp lib/catalina.jar org.apache.catalina.util.ServerInfo

**Comment by nickmcsimpson** [comment]
No dice.
![image](https://user-images.githubusercontent.com/25393558/97035745-66a89280-152c-11eb-998f-0943cadf43e0.png)

**Comment by zengkid** [comment]
@nickmcsimpson please open a project and setup the project JDK first. and then add tomcat server.

**Comment by nickmcsimpson** [comment]
Not quite sure what you're asking me to do. The project is setup in IntelliJ to use Java11. The _SDK_ is chose in the Project Structure menu. I can use the 'Choose Runtime' plugin and also choose Java11. Can you explain what you mean by 'setup the project JDK?'

**Comment by zengkid** [comment]
@nickmcsimpson I have try to load property file instead of executing java command to get tomcat info. 
I have build a new version in GitHub, will publish the plugin soon.
could you try to download [SmartTomcat-3.8.2](https://github.com/zengkid/SmartTomcat/releases/download/release3.8.2/SmartTomcat-3.8.2.jar) and install the plugin from disk?

**Comment by athaisyah** [comment]
> @nickmcsimpson I have try to load property file instead of executing java command to get tomcat info.
> I have build a new version in GitHub, will publish the plugin soon.
> could you try to download [SmartTomcat-3.8.2](https://github.com/zengkid/SmartTomcat/releases/download/release3.8.2/SmartTomcat-3.8.2.jar) and install the plugin from disk?

Thanksss!! it does working now. 👍 :) 
I install the plugin using  SmartTomcat-3.8.2, as per your suggestion
thanks in advancee
