### ISSUE TITLE
Slow context menu on editor after install plugin

### ISSUE THREAD

**Issue by gregory-bonassina** [zengkid/SmartTomcat#121]
After installing the plugin the context menu in the editor takes a while to load, if I disable the plugin the context menu becomes fast again

**Comment by yuezk** [comment]
@gregory-bonassina This plugin will try to register a context menu to start Tomcat quickly, by trying to populate the proper configuration based on the project structure. Is your project very large?

**Comment by gregory-bonassina** [comment]
> @gregory-bonassina This plugin will try to register a context menu to start Tomcat quickly, by trying to populate the proper configuration based on the project structure. Is your project very large?

Yes, my project structure is quite large, is there a way to disable this? Or something I can do to make the menu faster?

**Comment by yuezk** [comment]
Looks like this feature is not so useful, I never use it. I will turn off this feature by default.

**Comment by yuezk** [comment]
Released in 4.7.2, will be available in 24 hours.
