### ISSUE TITLE
Missing https Port configuration

### ISSUE THREAD

**Issue by emi-emi671** [zengkid/SmartTomcat#123]
Is this plugin support running the server over https?

**Comment by yuezk** [comment]
Yes. But need some configurations, below are my configurations.

1. Prepare the certificate (I'm using [mkcert](https://github.com/FiloSottile/mkcert) to generate the dev certs)
2. Configure the `<Tomcat Home>/conf/server.xml` for the Tomcat server you selected.
    ```xml
    <Connector port="8443" protocol="org.apache.coyote.http11.Http11NioProtocol"
               maxThreads="150" SSLEnabled="true"
            compression="on"
            compressableMimeType="text/html,text/json,application/json,text/xml,text/plain,application/javascript,text/css,text/javascript,text/js"
            useSendfile="false"
            compressionMinSize="500"
            >
        <!--<UpgradeProtocol className="org.apache.coyote.http2.Http2Protocol" />-->
        <SSLHostConfig>
            <Certificate certificateKeyFile="/path/to/localhost+3-key.pem"
                         certificateFile="/path/to/localhost+3.pem"
                         type="RSA" />
        </SSLHostConfig>
    </Connector>
    ```
3. Configure the SSL port in the Tomcat Configuration of IntelliJ
    <img width="661" alt="image" src="https://github.com/zengkid/SmartTomcat/assets/3297602/433952c7-3bca-4f72-a14f-f170f4805cd4">
4. Start the Tomcat, you could see the URL printed.
    <img width="404" alt="image" src="https://github.com/zengkid/SmartTomcat/assets/3297602/f987248c-dc65-4c19-9aad-d21e53a7425c">

**Comment by emi-emi671** [comment]
Thanks for sharing this, it seems to be working now after adding Connector port="8443" in server.xml.
One off-side question, it is working on Firefox but accessing the website on Chrome is not working. Do you have any idea about it?

**Comment by yuezk** [comment]
Glad it works for you. Closing.
