### ISSUE TITLE
SmartTomcat Plugin not working in Ubuntu

### ISSUE THREAD

**Issue by piratesouravshaw** [zengkid/SmartTomcat#124]
**Describe the bug**
I am using community edition of Intellij in my ubuntu machine 22.04.3. From market place when I try to install the plugin for the moment it mark it as installed but just after closing the marketplace window, smart tomcat plugin is no where to be found i.e., it is not listed as the installed plugin, even restarting IDE does not solve this issue. Meanwhile in marketplace it again asks for installation.  Hence, smart tomcat plugin is not getting installed in ubuntu based os in intellij.

**Screenshots**
![1008_572_1](https://github.com/zengkid/SmartTomcat/assets/60873612/01637f53-8ecc-4ce2-8676-7f760d4237fd)
![997_544_1](https://github.com/zengkid/SmartTomcat/assets/60873612/006b3e6d-1c2f-4edf-a4bd-0fd6812f9337)

**Intellij & SmartTomcat Version (Help -> About copy & paste below)**

**Comment by yuezk** [comment]
Hi @piratesouravshaw I couldn't reproduce this problem with the latest IntelliJ Community 2023.3.6, in Manjaro Linux.

What's the version of the IntelliJ are you using?

**Comment by piratesouravshaw** [comment]
Hi, I have updated my IntelliI IDEA to the latest community edition but still the issue persists

**Comment by yuezk** [comment]
@piratesouravshaw Try this:

1. Uninstall the SmartTomcat from the Plugins
2. Download the plugin JAR file from https://github.com/zengkid/SmartTomcat/releases/tag/release4.7.2
3. Open Plugins, install SmartTomcat from disk
    <img width="491" alt="image" src="https://github.com/zengkid/SmartTomcat/assets/3297602/8fc90dba-f9d0-4d9f-a91f-31fdb40b8faa">
4. Restart the IDEA
5. Check whether the plugin is installed and pay attention if there are errors reported by IDEA
    <img width="339" alt="image" src="https://github.com/zengkid/SmartTomcat/assets/3297602/2fc6a5da-c17e-455a-b8f3-78022efcf0ae">

**Comment by piratesouravshaw** [comment]
Thanks @yuezk was able to install the plugin successfully.
