### ISSUE TITLE
Cannot add Tomcat server from default location

### ISSUE THREAD

**Issue by RaraAvis8** [zengkid/SmartTomcat#13]
Windows 10, IntelliJ IDEA 2018.1.3 CE, Smart Tomcat 2.5, Tomcat 8.

Problem appears when Tomcat is located in default location in Windows:
`C:\Program Files\Apache Software Foundation\Tomcat 8.0`
When I try to add Tomcat Server in plugin settings then server name and version are not recognized.
![screenshot](https://user-images.githubusercontent.com/1635987/40164636-c85b70ba-59c2-11e8-92b9-78a17c85707a.jpg)

But if I move Tomcat to `C:\Tomcat8` folder then addition of the server works fine.

Probably there are some characters in folder path which create a problem.

**Comment by yl-coder** [comment]
Similar problem with #12.
