### ISSUE TITLE
start Tomcat is so slow

### ISSUE THREAD

**Issue by lyx2246** [zengkid/SmartTomcat#131]
**Describe the bug**

My APP's size is about 218Mb,When I deployed it to tomcat and start tomcat  directly,It's fast. It spent about 70 second. But when I start it in idea( IntelliJ IDEA community)with smarttomcat plugin,It spet more than 360s.  IT'S normal?
Thanks

**Screenshots**

**Intellij & SmartTomcat Version (Help -> About copy & paste below)**

**Comment by yuezk** [comment]
@lyx2246 you can try to disable the breakpoints and start to see if it is still so slow.

**Comment by lyx2246** [comment]
I don't set any breakpiont yet. Has anyone encountered this problem before?

**Comment by lyx2246** [comment]
@yuezk

**Comment by yuezk** [comment]
@lyx2246 I have a big project and it starts very slow if the breakpoints are enabled. But the same project on my colleague doesn't have this problem even though the breakpoints are enabled. So it's weird.

You can just give it a try to disable the breakpoints even though you don't set any breakpoints.

**Comment by lyx2246** [comment]
@yuezk 
Perhaps I have found the reason. I compared these two ways and found that the difference lies in loading the required jar files for the application. The direct startup way is because the jar packages are already centralized in the lib directory, while when using the idea, it  must read the configuration from the XML file in the Catalina/localhost/directory and load them one by one. There is no difference in other aspects.
Is there any good way?

> @lyx2246 I have a big project and it starts very slow if the breakpoints are enabled. But the same project on my colleague doesn't have this problem even though the breakpoints are enabled. So it's weird.
> 
> You can just give it a try to disable the breakpoints even though you don't set any breakpoints.



> @lyx2246 I have a big project and it starts very slow if the breakpoints are enabled. But the same project on my colleague doesn't have this problem even though the breakpoints are enabled. So it's weird.
> 
> You can just give it a try to disable the breakpoints even though you don't set any breakpoints.

**Comment by yuezk** [comment]
@lyx2246 The decentralized library is expected to impact the startup's performance. I noticed this as well. But it's not so significant based on my observation. For me, the direct start takes ~40 seconds. In SmartTomcat, with the breakpoint disabled, it tasks ~70 seconds, which is still acceptable. But if I enable the breakpoints, it takes several minutes to start.

I'm wondering if you have compared the start time with enabling and disabling the breakpoints. And I'm curious about the comparison.

**Comment by lyx2246** [comment]
@yuezk I run it with running mode,not debugging mode yet.

**Comment by yuezk** [comment]
I see, then I think this may not related to the debugging mode. It is probably due to the decentralized library in SmartTomcat.

**Comment by yuezk** [comment]
@lyx2246 you can try to install this build to see if it works. It won't register the decentralized jar if it already exists in the `WEB-INF/lib` folder.


[unzip_me.zip](https://github.com/user-attachments/files/17433274/unzip_me.zip)

**Comment by lyx2246** [comment]
> @lyx2246 you can try to install this build to see if it works. It won't register the decentralized jar if it already exists in the `WEB-INF/lib` folder.
> 
> [unzip_me.zip](https://github.com/user-attachments/files/17433274/unzip_me.zip)

@yuezk  I tried. The plugin still generate multiple lines for all jar files one by one in xml file.
I have already found the simple solution and validate it worked.
In the xml file,just generate one line to load all the jars instead of many lines to load them one by one. Like this:
<PostResources base="D: /ws/ftps/xfunds/funds/target/funds /WEB-INF/lib" className="or
g. apache catalina.webresources. DirResourceset" webAppMount="/WEB-INF/lib"/>

The lib and classes in the same directory WEB-INF。

Would you please modify the plugin? Thanks a lot.

**Comment by yuezk** [comment]
@lyx2246 your comments seem broken, where is the example?

**Comment by lyx2246** [comment]
@yuezk  sorry😓
<PostResources base="D: /ws/ftps/xfunds/funds/target/funds /WEB-INF/lib" className="or
g. apache catalina.webresources. DirResourceset" webAppMount="/WEB-INF/lib"/>

**Comment by lyx2246** [comment]
@yuezk  
PostResources base="D: /ws/ftps/xfunds/funds/target/funds /WEB-INF/lib" className="or
g. apache catalina.webresources. DirResourceset" webAppMount="/WEB-INF/lib"

**Comment by lyx2246** [comment]
Indeed, any '<\>' was intercepted

**Comment by yuezk** [comment]
@lyx2246 try this one.

[unzip_me.zip](https://github.com/user-attachments/files/17436901/unzip_me.zip)

**Comment by lyx2246** [comment]
@yuezk 
Oh, this one still generated some other jars (about 30) in the xml file,it's still slow.Just generating two lines  is enough.one line for classes,the other for lib.
I'm waiting for you reply,and will try again,thanks!

**Comment by lyx2246** [comment]
The current project refer other projects。Don't  generate lines for the referred projects.only the current project's classes and lib is enough.

**Comment by yuezk** [comment]
Can you post the generated xml here? I want to see what are included.

**Comment by lyx2246** [comment]
Wait for me to come back to the company on Monday

**Comment by lyx2246** [comment]
@yuezk 
![IMG_2126](https://github.com/user-attachments/assets/3e0aa37a-1d0c-48cd-ac4f-f2f29717067d)

**Comment by lyx2246** [comment]
Just need the two lines in the shaded area, the other lines are redundant and do not need to be generated because they are already included in the lib directory。

**Comment by lyx2246** [comment]
@yuezk 
Do you have WeChat?

**Comment by yuezk** [comment]
`echo "c2NyaXB0amF2YQ==" | base64 -d`

**Comment by lyx2246** [comment]
It's worked！thanks a lot.
