### ISSUE TITLE
Where does the SmartTomcat just copy the web.xml from?

### ISSUE THREAD

**Issue by AlvinZyhalj** [zengkid/SmartTomcat#132]
**Describe the bug**
I configured the Tomcat Server to the C:\works\apps\apache-tomcat-9.0.64 folder and changed the C:\works\apps\apache-tomcat-9.0.64\conf\web.xml file to add some filter definitions, but SmartTomcat always finds an old web.xml file to apply. 

I can see the file C:\Users\<User>\.SmartTomcat\<project>\conf\web.xml was rolled back when the SmatTomcat instance was launched. Even if I manually change it. 

Where does the SmartTomcat just copy the web.xml from?

**Screenshots**
Here is my SmartTomcat plugin config.
![image](https://github.com/user-attachments/assets/4146ba58-679d-4196-8228-3edb5b9807c7)

**Intellij & SmartTomcat Version (Help -> About copy & paste below)**
IntelliJ IDEA 2024.1 (Community Edition)
Build #IC-241.14494.240, built on March 28, 2024
Runtime version: 17.0.10+8-b1207.12 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4056M
Cores: 20
Registry:
  ide.experimental.ui=true
Non-Bundled Plugins:
  org.summer.export2Local (1.7)
  Lombook Plugin (241.14494.240)
  com.poratu.idea.plugins.tomcat (4.7.3)
  com.yiycf.plugins.mavenDependencyHelper (2.5)
  MavenRunHelper (4.29.0-IJ2022.2)
Kotlin: 241.14494.240-IJ

SmartTomcat: 4.7.3

**Comment by yuezk** [comment]
@AlvinZyhalj SmartTomcat 4.7.3 will create  a .smarttomcat folder in your project and copy the configuration files there . You can change the configuration files there and it will take effect.

**Comment by AlvinZyhalj** [comment]
@yuezk  Great! Changing C:\works\projects\<project>\.smarttomcat\**server**\conf\web.xml file can work.
