### ISSUE TITLE
is it possible to hotswap java class change with this plugin?

### ISSUE THREAD

**Issue by taojinjing** [zengkid/SmartTomcat#15]
is it possible to hotswap java class change with this plugin?

**Comment by zengkid** [comment]
doesn't support method signature changes and new class/method 

only support code changes in method

**Comment by yarix** [comment]
first, thank you for this great plugin
second, how does class reloading should work? i don't see it reloads even when i change only the code inside a method.
thank you.

source is in:
src/main/java ==> classes aren't updated (need to restart the plugin or build the project)
src/main/webapp ==>jsp, html and resources are updated upon changes.

**Comment by zengkid** [comment]
> first, thank you for this great plugin
> second, how does class reloading should work? i don't see it reloads even when i change only the code inside a method.
> thank you.
> 
> source is in:
> src/main/java ==> classes aren't updated (need to restart the plugin or build the project)
> src/main/webapp ==>jsp, html and resources are updated upon changes.

for java code src/main/java changed, need build the project or module (shortcut: ctrl+ f9), and then will auto reload the changed.
for webapp files src/main/webapp changed, no need build.
