### ISSUE TITLE
NullPointerException after updating IntelliJ

### ISSUE THREAD

**Issue by oosterholt** [zengkid/SmartTomcat#17]
Every time after an IntelliJ update, a NullPointerException occurs when starting tomcat.
Error displayed:

`Error running 'Tomcat': java.lang.NullPointerException`

There seems not to be any more logging than that.
It can only be fixed by completely removing the Smart Tomcat configuration and adding a new one.

**Comment by peterkhang** [comment]
me too

**Comment by evguenig** [comment]
2.0 works fine - as soon as I upgrade to 2.6 - I have NPE mentioned above.
Is there any way to run plugin in verbose mode or get some run logs?

**Comment by walkwolf** [comment]
me too. v2.6 win10 idea:2018.03CE

**Comment by paoloyx** [comment]
Hi, i'm unable too to use the plugin. My laptop==> **OSX:10.13.1, plugin:v2.6, idea:2018.3.5**

`Error running 'tomcat': java.lang.NullPointerException`

**Comment by wizofaus** [comment]
Still happening for me with latest plugin, haven't been able to solve at all.

**Comment by zengkid** [comment]
@wizofaus  could you share intellij idea and smarttomcat version?

**Comment by zengkid** [comment]
> Still happening for me with latest plugin, haven't been able to solve at all.

@wizofaus could you share intellij idea and smarttomcat version?

**Comment by wizofaus** [comment]
Actually it turns out the upgrade hadn't worked for some reason, after re-upgrading and re-starting and re-creating the configuration all is good, thanks!
