### ISSUE TITLE
how to set catalina_home and catalina_base

### ISSUE THREAD

**Issue by buruoyanyang** [zengkid/SmartTomcat#18]
hi,i can add tomcat and run it, but it is not working.i can not use my url.
in starting info, i can  see  that catalina_base and catalina_home is C:\Users\xxx\.SmartTomcat\xxx\xxx
i set env options, but it not work.so  how to set it?
thank you.

**Comment by zengkid** [comment]
can you provide the log?

Regards
Kid

________________________________
