### ISSUE TITLE
Can not add tomcat server

### ISSUE THREAD

**Issue by xiaotown123** [zengkid/SmartTomcat#19]
I add a tomcat server, but there is nothing to show. 
![image](https://user-images.githubusercontent.com/6803181/51517968-737bec00-1e57-11e9-9b46-96c494396e85.png)

This is the error message, it seems like using some old configure.

![image](https://user-images.githubusercontent.com/6803181/51517987-84c4f880-1e57-11e9-96d5-888c15c0d481.png)

**Comment by xiaotown123** [comment]
![image](https://user-images.githubusercontent.com/6803181/51518241-349a6600-1e58-11e9-802b-cfd63522f39a.png)
SmartTomcat version is v2.6.

**Comment by akuma8** [comment]
I have a quite similar issue with the same version, I just can't choose a webapp folder

**Comment by zryengytj** [comment]
select tomcat home path: /xxx/xxx/tomcat

**Comment by zengkid** [comment]
please setup the jdk in project first.
![image](https://user-images.githubusercontent.com/3382739/64475629-a214c000-d1b7-11e9-9d8d-0175f32c7a5d.png)
