### ISSUE TITLE
Create multiple Tomcat Server doesn't work

### ISSUE THREAD

**Issue by open-it** [zengkid/SmartTomcat#23]
In my project, I need 3 differents Tomcat server. It's the same version but with different classpath and config. When I create the first one, it is called "Apache Tomcat 8.0.43" and I can't change its name. Then I create a second one, its name is "Apache Tomcat 8.0.43 (1)", it's not really easy to remember but it's OK. BUT the third one is named  "Apache Tomcat 8.0.43 (1)" too ! And the third one takes the classpath and config from the second one (when I look into C:\Users\{me}\.SmartTomcat\{project}\{project}. If I change manually, the plugin doesn't keep my changes.
Hope it's clear enough.

**Comment by zengkid** [comment]
I think you can use 3 differences  ports for 3 projects (servers)
