### ISSUE TITLE
Receiving Null Pointer Exception

### ISSUE THREAD

**Issue by surapuramakhil** [zengkid/SmartTomcat#25]
7:28 PM	Error running 'tomcat 9': java.lang.NullPointerException from Intellij 2k19 community Edition

**Comment by surapuramakhil** [comment]
ready to help if any more information is required

**Comment by zengkid** [comment]
have you setup the jdk in your project first?

**Comment by surapuramakhil** [comment]
Yes

**Comment by surapuramakhil** [comment]
Its has two Jdk. one is Jdk 1.8 and Intellj JDK. 
and I have configured to run it on Oracle JDK 1.8

**Comment by zengkid** [comment]
more error information?

**Comment by surapuramakhil** [comment]
We Can look for that. I have looked in intellij logs but couldn't find Any.

**Comment by surapuramakhil** [comment]
Hope this 
![Screenshot from 2019-09-28 20-51-30](https://user-images.githubusercontent.com/9161543/65818718-f13b9700-e231-11e9-8e86-a55c001fa63c.png)
Helps.

**Comment by surapuramakhil** [comment]
Hope this Helps.

![Screenshot from 2019-09-28 20-51-30](https://user-images.githubusercontent.com/9161543/65818751-48da0280-e232-11e9-8b3c-aec83b64e2e6.png)

**Comment by surapuramakhil** [comment]
Hope this helps.

![Screenshot from 2019-09-28 20-54-59](https://user-images.githubusercontent.com/9161543/65818754-5db69600-e232-11e9-957e-9313de0eeb0e.png)

**Comment by zengkid** [comment]
please try the latest version 3.0.1
