### ISSUE TITLE
receinving exception on running. I have set tomcat location

### ISSUE THREAD

**Issue by surapuramakhil** [zengkid/SmartTomcat#27]
-PFA screenshot Error and Conf.

I know its an exception thrown by the plugin. I am getting this after I have set tomcat location has been set
![Screenshot from 2019-10-01 09-05-12](https://user-images.githubusercontent.com/9161543/65932263-991bb500-e42a-11e9-80df-6d24869dda94.png)
![Screenshot from 2019-10-01 09-10-13](https://user-images.githubusercontent.com/9161543/65932430-50b0c700-e42b-11e9-8880-4263539976cf.png)

![Screenshot from 2019-10-01 09-01-58](https://user-images.githubusercontent.com/9161543/65932180-30ccd380-e42a-11e9-877c-49c53a7bf1ca.png)

- feel free to contact for any additional info

**Comment by zengkid** [comment]
please change the deployment to <project_location>/webapp. 
the webapp is a standard maven or gradle or jetbrain idea project struct. then the plugin will find the module root.
