### ISSUE TITLE
Text boxes in configuration has problem of typing for left to right.

### ISSUE THREAD

**Issue by surapuramakhil** [zengkid/SmartTomcat#28]
It seems that text boxes are of right to left

**Comment by zengkid** [comment]
which field? I can not find the issue.

**Comment by rsippl** [comment]
I think he's referring to the "Deployment Dir" field in the "Run/Debug configurations" dialog. Type in "abc" and you'll get "cba".

**Comment by zengkid** [comment]
the java swing issue.
