### ISSUE TITLE
webapp没有读取maven编译后的web.xml

### ISSUE THREAD

**Issue by fevenor** [zengkid/SmartTomcat#3]
我们的maven项目，根据运行环境，编译时对web.xml进行了变量替换。SmartTomcat在运行时，读取的是原始的web.xml文件，而非编译后target目录下的web.xml。

**Comment by zengkid** [comment]
这种情况暂时不支持，我这个插件是直接指向开发目录的。
也就是配置的Deployment直接配置<project>/webapp就可以了。
这个webapp是一个完整的war目录，但是不用包括jar和classes。
