### ISSUE TITLE
Additional context parameters

### ISSUE THREAD

**Issue by Bruce17** [zengkid/SmartTomcat#32]
Hi,

I'm using custom context parameter and resource elements in `server.xml` to adjust my `<Context>...</Context>` e.g.:

```xml
<Context ...>
  ...
  <Parameter name="mail.sender" value="noreply@example.com" override="false"/>
  <Resource  name="mail/Session" type="javax.mail.Session" mail.smtp.host="my.smtp.server"/>
  ...
</Context>
```

The `server.xml` and `context.xml` get's overwritten on every run of the plugin. How can I inject that properties into the `server.xml`?

**Comment by zengkid** [comment]
@Bruce17 sorry,  the plugin not supported the feature  so far

I will consider whether to support this feature.

**Comment by zengkid** [comment]
updated in release3.5.0
