### ISSUE TITLE
Selecting a tomcat directory does not correctly detect the server

### ISSUE THREAD

**Issue by christkv** [zengkid/SmartTomcat#33]
I'm not able to configure the tomcat server anymore after Intellij update, picking the directory just leads to the screenshot as shown. I have jdk 8 configured for the project.

IntelliJ IDEA 2019.3 (Community Edition)
Build #IC-193.5233.102, built on November 28, 2019
Runtime version: 11.0.4+10-b520.11 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.6
GC: ParNew, ConcurrentMarkSweep
Memory: 8012M
Cores: 12
Registry: 
Non-Bundled Plugins: com.poratu.idea.plugins.tomcat, org.jetbrains.kotlin

![Screenshot 2019-12-09 at 01 12 48](https://user-images.githubusercontent.com/5569/70399081-840e6400-1a21-11ea-8d5a-9744a50c11e0.png)

**Comment by zengkid** [comment]
closed in release3.5.0

**Comment by prachiagrawal269** [comment]
I'm still seeing this issue even with the IntelliJ 3.5.0 version. Any suggestions on how to resolve this?

**Comment by zengkid** [comment]
> @zengkid I'm still seeing this issue even with the IntelliJ 3.5.0 version. Any suggestions on how to resolve this?
@prachiagrawal269 which Intellij Idea version? please try to reinstall the plugin.

**Comment by EXS8614** [comment]
I'm having the same issue on Windows 10 with new plugin
