### ISSUE TITLE
热部署

### ISSUE THREAD

**Issue by haominglfs** [zengkid/SmartTomcat#36]
修改java文件，热部署不生效

**Comment by zengkid** [comment]
方法签名的修改，重命名或者添加参数之类的，还是删除和添加新的方法，这些都不支持热部署。
方法内的代码修改是支持热部署的。

**Comment by haominglfs** [comment]
idea版本:
IntelliJ IDEA 2019.3 (Community Edition)
Build #IC-193.5233.102, built on November 28, 2019 Runtime version: 11.0.4+10-b520.11 x8664
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
smart tomcat版本3.5.0
tomcat版本8.5.50.0
笔记本是mac
添加一条输出语句
![image](https://user-images.githubusercontent.com/7012774/72678405-8532b680-3ae0-11ea-8f23-e3ffc6e44ff9.png)
运行的时候并没有生效，请问需要做额外的配置使热部署生效吗？

**Comment by zengkid** [comment]
ctrl+f9编译一下就会reload了。

**Comment by haominglfs** [comment]
好的，非常感谢！
