### ISSUE TITLE
Tomcat Server null

### ISSUE THREAD

**Issue by edubranquinho** [zengkid/SmartTomcat#37]
Hello.

I'm trying to add a tomcat server using Smart Tomcat but i'm not able to do so.
Tomcat name and Tomcat Version are empty.
Image below:

![image](https://user-images.githubusercontent.com/11495674/72613087-5f08ed00-390d-11ea-9fb1-ff1fb88d3308.png)

I'm using MacOs, Smart Tomcat V3.0.2. 
Intellij: 
IntelliJ IDEA 2018.3.6 (Community Edition)
Build #IC-183.6156.11, built on March 25, 2019
JRE: 1.8.0_152-release-1343-b28 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6

I tried to upgrade Smart Tomcat by installing it manually (dropping its file in plugin folder) but it says is not compatible with my version of Intellij.

**Comment by zengkid** [comment]
Hi, Guys, please upgrade Intellij Idea to 2019.3+ version, and then update smarttomcat plugin to 3.5 version.

**Comment by edubranquinho** [comment]
Okay zengkid.

Just to let you know, in my case i downgrade my Smart Tomcat to 2.6 and it worked.
I'll work now to upgrade ST to 3.5 and Intellij to latest version. After i do that, i'll test the integration and let you know if everything worked fine.
Thanks.

**Comment by mouday** [comment]
good
