### ISSUE TITLE
Latest releases of Tomcat (8.5.51 and 9.0.31) no longer work

### ISSUE THREAD

**Issue by oosterholt** [zengkid/SmartTomcat#38]
When using the latest versions of Tomcat 8.x and 9.x, the plugin stops working and briefly shows a NullPointerException.

Tomcat 8.5.50/9.0.30 both work
Tomcat 8.5.51/9.0.31 stopped working and shows a NullPointerException.

![image](https://user-images.githubusercontent.com/730953/74747065-a238e180-5266-11ea-9741-86ad8c7a1745.png)

`Error running '[Configuration name]': java.lang.NullPointerException`

**Comment by zengkid** [comment]
the tomcat have updated config/server.xml default setting.

AJP disable as default. in order to fix the issue, you can  uncomment AJP element or waiting my update.

 ` `

**Comment by zengkid** [comment]
fixed

**Comment by oosterholt** [comment]
Wow, that's a fast fix. 

Starting Tomcat is fixed indeed, but starting Tomcat in debug mode stopped working now.

I think users expect running in debug mode should work out of the box after installing Tomcat/Smart Tomcat without having to change anything in the Tomcat installation I think. 

Can running debug mode also be fixed, or can a 'how to' be added to the plugin / Github page?

**Comment by zengkid** [comment]
@oosterholt  I have running in debug mode. it works

Have you upgrade the plugin to release3.6.0?

you can download the plugin release [https://github.com/zengkid/SmartTomcat/releases](url)

**Comment by oosterholt** [comment]
I was already at the updated version; I re-tried and now it works like a charm! thanks again.
