### ISSUE TITLE
Multiple webapp support

### ISSUE THREAD

**Issue by manikantag** [zengkid/SmartTomcat#39]
Hi,

Does SmartTomcat supports adding multiple webapps to tomcat _(like in Eclipse)_?

**Comment by zengkid** [comment]
@manikantag  not support it.

**Comment by manikantag** [comment]
Ok, thanks for the confirmation. Do you plan to support it?

**Comment by zengkid** [comment]
No plan recently, you can create multiple run/debug to support it.

**Comment by manikantag** [comment]
Yes, I can. But the problem here is I've total 4 webapps and they all talk to each other on same port. I need to change in the existing config files in my local copy and fiddle with git merges. Just checking if is there a easier way. Thanks

**Comment by yuezk** [comment]
@manikantag I would like to support this feature, is there any configuration UI that I can refer?

**Comment by manikantag** [comment]
@yuezk Good to know. But I've moved to ultimate edition and no longer using this. I'll try to find older config, if I've one laying around. Thanks
