### ISSUE TITLE
Create maven plugin to ease integration with maven

### ISSUE THREAD

**Issue by dedece35** [zengkid/SmartTomcat#40]
In order to integrate your plugin SmartTomcat with maven, I think it's a quite good idea to create a maven plugin that can automatically create a default SmartTomcat configuration in IntelliJ.
This is to avoid manual configuration of Smart Tomcat

**Comment by zengkid** [comment]
show a short cut run in SmartTomcat when right click context menu in webapp folder.
hope you like this.
