### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by dejj** [zengkid/SmartTomcat#41]
I set up some configuration, with some tomcat instance, and a webapp.
I'm running plugin version v3.0.2 on Windows 7, IntelliJ CE 2019.1
When I click "run", Event Log shows the following error message:

> Error running 'MyProject Tomcat': java.langNullPointerException

Does the plugin create a logfile?
Can I debug the plugin short of compiling it?

**Comment by zengkid** [comment]
> I set up some configuration, with some tomcat instance, and a webapp.
> I'm running plugin version v3.0.2 on Windows 7, IntelliJ CE 2019.1
> When I click "run", Event Log shows the following error message:
> 
> > Error running 'MyProject Tomcat': java.langNullPointerException
> 
> Does the plugin create a logfile?
> Can I debug the plugin short of compiling it?

please update intellij ce 2019.3 version and smart tomcat 3.6.0 version
