### ISSUE TITLE
How to add external folder to CLASSPATH?

### ISSUE THREAD

**Issue by zizifn** [zengkid/SmartTomcat#43]
My project needs an external folder as classpath, normal I would add `setenv.bat` in `tomcat\bin`  and start tomcat by using `catalina.bat`. But it seems I can't do this by using SmartTomcat.

**Comment by zengkid** [comment]
> My project needs an external folder as classpath, normal I would add `setenv.bat` in `tomcat\bin` and start tomcat by using `catalina.bat`. But it seems I can't do this by using SmartTomcat.

you can put the external folder or jars into Dependencies in project (webapp mudule).
![image](https://user-images.githubusercontent.com/3382739/80963261-2996f980-8e41-11ea-98ee-81c9b77fb1db.png)

**Comment by zizifn** [comment]
> > My project needs an external folder as classpath, normal I would add `setenv.bat` in `tomcat\bin` and start tomcat by using `catalina.bat`. But it seems I can't do this by using SmartTomcat.
> 
> you can put the external folder or jars into Dependencies in project (webapp mudule).
> ![image](https://user-images.githubusercontent.com/3382739/80963261-2996f980-8e41-11ea-98ee-81c9b77fb1db.png)


Thanks for the quick reply, but which item should same as eclipse tomcat user entries(Add folders).

![image](https://user-images.githubusercontent.com/1803942/80964380-54824d00-8e43-11ea-8024-78012fe4c45f.png)

**Comment by zengkid** [comment]
@zizifn 
if you can't put the folder into project dependencies,  you can pack the classpath folder to a jar file, and then put  jars into tomcat_home\lib.

**Comment by zengkid** [comment]
you can put the folder in tomcat_home\lib, and then rename to xxx.jar folder to cheat the system

**Comment by zizifn** [comment]
> @zizifn you can put the folder in tomcat_home\lib, and then rename to xxx.jar folder to cheat the system

Thanks, I fixed this by add folder in `tomcat_home\conf\catalina.properties`, i will try your solcution when i got time..
```
shared.loader="C:/**","C:/**"
```
