### ISSUE TITLE
How to use env options in VM options?

### ISSUE THREAD

**Issue by zizifn** [zengkid/SmartTomcat#44]
I want to use env variable in VM options. So i setup below is my config, but this will not working..
![image](https://user-images.githubusercontent.com/1803942/81056887-f7979d00-8efd-11ea-8985-178a59a5d0a2.png)

**Comment by zengkid** [comment]
VM options not support variable value.
-Dtest1111=envTest1

**Comment by zizifn** [comment]
> VM options not support variable value.
> -Dtest1111=envTest1

Thanks! oh...Tomcat in eclipse doing the trick for me.

**Comment by zizifn** [comment]
@zengkid does this plugin have some internal variable for project location?

**Comment by zengkid** [comment]
@zizifn  why not use Env variable directly?

**Comment by zizifn** [comment]
> @zizifn why not use Env variable directly?

It seems I can't get Env variable in my `log4j.xml` and `tomcat_home\conf\catalina.properties`, but i can get VM args in these file by using `${vaiableName}`.

**Comment by zengkid** [comment]
@zizifn please try to add the variable into your computer Environment.

**Comment by zizifn** [comment]
> @zizifn please try to add the variable into your computer Environment.

Thanks! Add into window env and echo variable in `cmd`, restart IDEA and still `tomcat_home\conf\catalina.properties` can't get variable value.

**Comment by zengkid** [comment]
what do you config in tomcat_home\conf\catalina.properties? 
and what do you want?

**Comment by zengkid** [comment]
and I have debug the  VM value from env.
you can try to check your idea console the first line. the plugin call to start the tomcat by command line.
![image](https://user-images.githubusercontent.com/3382739/81076478-42291180-8f1e-11ea-8113-4f2be16bc26b.png)

**Comment by zizifn** [comment]
> and I have debug the VM value from env.
> you can try to check your idea console the first line. the plugin call to start the tomcat by command line.
> ![image](https://user-images.githubusercontent.com/3382739/81076478-42291180-8f1e-11ea-8113-4f2be16bc26b.png)

Thanks! Set env in computer + reference env in VM args, work fine.(I forget reference env in my testing). Is possible Smart Tomcat can make env work when I set in IDEA run/debug configuration?
![image](https://user-images.githubusercontent.com/1803942/81077539-ac8e8180-8f1f-11ea-9ab9-a57fd613e436.png)

**Comment by zengkid** [comment]
@zizifn  In fact, IDEA SDK only get computer Env to pass the data. I will try my best to find a way to support the feature in next version.

**Comment by zizifn** [comment]
> @zizifn In fact, IDEA SDK only get computer Env to pass the data. I will try my best to find a way to support the feature in next version.

Thanks very much! I'm fine with this and please close this issue if you want.

**Comment by zengkid** [comment]
@zizifn Another alternative you can add into Path Variable.
![Uploading image.png…]()
