### ISSUE TITLE
Modifications are not hot reloaded anymore

### ISSUE THREAD

**Issue by optyler** [zengkid/SmartTomcat#46]
Hi, I have updated few days ago to the release3.6.1 and now I'am on the last revision, but since the release3.6.1, all changes made in my src groovy files are not hot reloaded by the plugin, even if a run a full project build (⌘ F9). Any suggestions ?

That worked pretty well before these updates.

**Comment by zengkid** [comment]
@optyler  Could you please try to reinstall to check? what's latest old version do you work?

**Comment by optyler** [comment]
I'm not 100% sure, but it should be : release3.5.0

fresly removed and re-installed the 3.6.3 version of the plugin, problem persists

**Comment by zengkid** [comment]
only for groovy files?

**Comment by optyler** [comment]
I only saw the problem on groovy files.

Well, I restarted a bunch of times Intellij since the problem occurs and lastly I no longer see the issue. I'll make an update here if the problem reappears. If that is the case, do you need some sort of logs or something ?
