### ISSUE TITLE
enable ssl  problem

### ISSUE THREAD

**Issue by cj900** [zengkid/SmartTomcat#47]
i try run the tomcat  with ssl enable but false; 
i  update  ./smarttomcat/project/xx/conf/server.xml  
add the 8443 port and ssl enable 
when i run  / debug  , it will override my setting / restore  to default?

how to config when i want to enable ssl support
thanks

**Comment by zengkid** [comment]
@cj900 please update the server.xml in $tomcat_home\config\server.

**Comment by cj900** [comment]
it's ok now
is that a plan to add ssl config  to the ui?
many thanks
