### ISSUE TITLE
改变代码 但是代码没有生效 

### ISSUE THREAD

**Issue by hg460713171** [zengkid/SmartTomcat#49]
maven项目  我改变代码 也重新编译过  target文件夹里的东西也是对的  但是使用smarttomcat 启动时 发现使用的是以前的代码 
感觉是有缓存的样子 
不知道里面是不是用了缓存  还是直接读取target里的东西  还是存放在其他地方
如果有缓存 我想知道缓存存放在哪   怎么清除缓存

**Comment by hg460713171** [comment]
找到原因了  vm参数制定了 catalina

**Comment by zengkid** [comment]
web目录设置为src下的webapp.

________________________________
