### ISSUE TITLE
tomcat7 cast to javax.servlet.Filter Exception

### ISSUE THREAD

**Issue by Alvison** [zengkid/SmartTomcat#5]
pom.xml java.servlet-2.5.jar ( provid scope ) present in server.xml ->Context->Loader->virtualClasspath.  cause castException

IntelliJ IDEA 2017.3.4 (Community Edition)

apache-maven-2.2.1

project compile using jdk7

deploy container: tomcat7.0.55

**Comment by zengkid** [comment]
please try to update version 1.9

**Comment by Alvison** [comment]
That is excatly what version(1.9) install in my idea.  Exception occur all the time
