### ISSUE TITLE
Where to find logs?

### ISSUE THREAD

**Issue by willroyMyles** [zengkid/SmartTomcat#50]
Goodday, is it possible to find logs from this plugin?

**Comment by zengkid** [comment]
> Goodday, is it possible to find logs from this plugin?

@willroyMyles  what do you need?

**Comment by willroyMyles** [comment]
@zengkid, using the regular tomcat server it has a logs folder where i can find logs from my application. i cannot find those logs with this plugin. my question is : 
where would i locate the log files?

**Comment by zengkid** [comment]
@willroyMyles please check the folder: C:\Users\<userid>\.SmartTomcat\<webmodule>\
