### ISSUE TITLE
Ability to redirect console output to a file

### ISSUE THREAD

**Issue by jamesanto** [zengkid/SmartTomcat#51]
Hi @zengkid, thanks for your great work!

Would it be possible to add the ability to redirect the console output to a file? Similar to other run configurations. I have attached a screenshot.

<img width="795" alt="Screenshot 2020-08-27 at 4 10 18 PM" src="https://user-images.githubusercontent.com/4387216/91432807-ea713600-e87f-11ea-8cf8-9a8a9951c540.png">

**Comment by zengkid** [comment]
@jamesanto do you mean tomcat log  ? you can find it in c:\users\<userid>\.SmartTomcat\<project>\<module>\logs

**Comment by zengkid** [comment]
add log tab in version 3.8.0

**Comment by jamesanto** [comment]
@zengkid I was away for a while, thanks for the update!
