### ISSUE TITLE
Servlet Annotation @PostConstruct & @PreDestroy issue

### ISSUE THREAD

**Issue by MagnusLeona** [zengkid/SmartTomcat#52]
I met up with a problem .  With tomcat@9.0.37 and servlet@4.0 and JDK 14.0, Servlet annotation @PostConstruct and @PreDestroy dont work running on smart tomcat, i just dont know what is happening , and i notice that they can work well on EnterPrise Version Tomcat Server. Plz check it, thank you

**Comment by zengkid** [comment]
I work fine with tomcat 9.0.35, you can try  the sample project [https://github.com/zengkid/smart-tomcat-sample](url)

![image](https://user-images.githubusercontent.com/3382739/91920259-17e43680-ecfb-11ea-8900-2f7891a8a0a7.png)

**Comment by MagnusLeona** [comment]
yeah i noticed it happend because i imported the wrong jar. i was supposed to import javax.annotation.jar instead of javax.annotation-api.jar.  And for all, thank you for your help ;)
