### ISSUE TITLE
Module not retrieved correctly any more

### ISSUE THREAD

**Issue by karge-itestra** [zengkid/SmartTomcat#55]
In the latest release, the module is saved in the configuration directly instead of the module name. In the multi-module project we run, the module seems to be null however. Previously, when the module was retrieved by the stored module name, it worked.

**Comment by karge-itestra** [comment]
The relevant lines of code to retrieve the project in the previous version were
`´`java
File file = new File(configuration.getDocBase());
VirtualFile fileByIoFile = LocalFileSystem.getInstance().findFileByIoFile(file);
Module module = ModuleUtilCore.findModuleForFile(fileByIoFile, configuration.getProject());
```

**Comment by zengkid** [comment]
@karge-itestra could you try to remove exists run/debug setting ?

**Comment by karge-itestra** [comment]
Will try, thanks for the advice. I have rolled back to 1.7.2 for now, is it possible to write a fix that converts existing configs?

**Comment by zengkid** [comment]
@karge-itestra in fact, I just refactor the code, the code should be same.

**Comment by etienne582** [comment]
Hello, I have the same problem with a multi module spring boot project.
To make tomcat start I need to just edit my tomcat config and then it work's ...
I also tried to save the configuration as project file but it changes nothing :/

**Comment by zengkid** [comment]
@etienne582  could you share screenshot and logs?

**Comment by etienne582** [comment]
![image](https://user-images.githubusercontent.com/15012429/94114477-b3734d80-fe48-11ea-9a32-37c89256e387.png)

This error log view of intellij display the same message : 
Error running 'Tomcat': The Module Root specified is not a module according to Intellij

I have nothing on the smartTomacat logs.

**Comment by zengkid** [comment]
@etienne582  Could you share project stuct and SmartTomcat run/debug infomation?

**Comment by yuezk** [comment]
@zengkid Here is an example of this problem.

https://github.com/yuezk/webapp-example-gradle

**Comment by zengkid** [comment]
@yuezk please choose a SDK for Project!
![image](https://user-images.githubusercontent.com/3382739/94364594-1ee54580-00fd-11eb-9bd7-a862b492becf.png)

**Comment by yuezk** [comment]
> @yuezk please choose a SDK for Project!
> 
> ![image](https://user-images.githubusercontent.com/3382739/94364594-1ee54580-00fd-11eb-9bd7-a862b492becf.png)
> 
> 

I'm using 1.8 on my local machine, you can choose yours (e.g., 1.8 or 11) on your machine and test it.

**Comment by zengkid** [comment]
@yuezk once I choose a SDK, it work fine for me.
which version for intellij idea?

**Comment by yuezk** [comment]
Wired. Below is the IDEA version.

```
IntelliJ IDEA 2020.2.2 (Community Edition)
Build #IC-202.7319.50, built on September 15, 2020
Runtime version: 11.0.8+10-b944.31 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 3005M
Cores: 8
Non-Bundled Plugins: IdeaVIM, SnakeYAML plugin, com.alayouni.ansiHighlight, com.intellij.ideolog, Lombook Plugin, com.poratu.idea.plugins.tomcat, training, org.jetbrains.kotlin, zielu.gittoolbox, com.cybrosis.catdea
```

**Comment by zengkid** [comment]
@yuezk  Could you provide your error message ?

**Comment by yuezk** [comment]
![image](https://user-images.githubusercontent.com/3297602/94386213-ae303e80-0179-11eb-9bfa-507743c9e71a.png)

**Comment by zengkid** [comment]
@yuezk  I got the same issue now, the issue caused by re-open the project.  for temporary solution, you can remove tomcat run/debug, and then add a new one.
I will fix soon. thanks

**Comment by yuezk** [comment]
@zengkid Yes, it worked with your workaround. Thanks.

**Comment by etienne582** [comment]
It's seems ok with the 3.8.1 thx

**Comment by karge-itestra** [comment]
Thanks for the reporting @etienne582 and @yuezk , and thanks for the fix @zengkid !
