### ISSUE TITLE
hot swap

### ISSUE THREAD

**Issue by mcelotti** [zengkid/SmartTomcat#56]
First of all thanks for the plugin!
Question: I'm working on a maven application, is it possible to hot swap code on my tomcat? I have standard setup, no special configs or customizations. I know some people suggest http://hotswapagent.org/ but I was wondering if I can get the same result using the plugin.

Thanks,
Marco

**Comment by zengkid** [comment]
@mcelotti only support add/remove/update code in method.  not support add new class or change method name or add/remove method parameters.

**Comment by mcelotti** [comment]
It works! Thank you @zengkid.
Here's what I did: http://hotswapagent.org/mydoc_setup_intellij_idea.html 

My VM options (I'm using macOS):
`-XXaltjvm=dcevm -javaagent:/Users/xxx/Library/ApplicationSupport/JetBrains/IdeaIC2020.2/plugins/hotswap-agent-intellij-plugin/lib/agent/hotswap-agent-1.4.1.jar`

Thanks,
Marco
