### ISSUE TITLE
Problem with "-Duser.region=US"

### ISSUE THREAD

**Issue by frendon** [zengkid/SmartTomcat#58]
HI,
My country is Spain and I need to set the JVM options to reflect this fact.

I set the variables in the JVM options, but they are always ignored.

`-Duser.language=es -Duser.country=ES -Duser.variant=ES`

The culprit is line 109 of the file  src/main/java/com/poratu/idea/plugins/tomcat/conf/AppCommandLineState.java

`
String options = "-Duser.language=en -Duser.region=US " + vmOptions; //set en_US as default
`

**Comment by zengkid** [comment]
@frendon I will remove the default setting in next version. thanks

**Comment by zengkid** [comment]
already remove default language region  VM options in 3.8.2
