### ISSUE TITLE
Generated web.xml with maven plugin

### ISSUE THREAD

**Issue by open-it** [zengkid/SmartTomcat#61]
Hello,

I am facing a problem with an old java / struts application which uses variables in **web.xml**.
Like this : 
```
<param-value>${var.url}</param-value>
```
Those variables are generated with a maven plugin : **maven-war-plugin**

I am not really sure how Smart Tomcat works but I think it is copying a Tomcat conf in my user's directory in the directory **.SmartTomcat** and when I look into the **server.xml** of my app (in my user's directory), I can see a reference to **src/main/webapp** and not the one generated in **target**

So I can see my app calling ${var.url}

:(

**Comment by zengkid** [comment]
you are right, Smart Tomcat reference to src/main/webapp/ but not target folder.
maybe not support your case now.

do you mean you want to reference target web.xml by manual to support your case?

**Comment by open-it** [comment]
Maybe this case is not a very common case you are right. 
But it would be great to be able to run SmartTomcat by selecting directly a .war file. This would have solved my problem. 
What I did is to run a Tomcat Server in Eclipse, I have to manually copy/paste the war file :( and I set a remoteDebug in IntelliJ. A bit complicated

**Comment by zengkid** [comment]
@open-it I am very sorry that SmartTomat won't support it. just as you said, you can run remoteDebug in intellij after building a war file.

**Comment by open-it** [comment]
I understand, thanks for the answer ;)
