### ISSUE TITLE
The Plugin does not permit select excluded IntelliJ directory as the deployment directory

### ISSUE THREAD

**Issue by mauricio-ms** [zengkid/SmartTomcat#64]
Hi,

I need to select the deployment directory as the target of my project, but this does not appear in the selection because is marked as excluded in the modules config of IntelliJ. If I mark as not excluded It works. But in this case the IntelliJ consider this in indexing proccess. If were possible permit select excluded directories it will be great.

Thanks.

IntelliJ IDEA 2020.3.2 (Community Edition)
Tomcat 9.0.19

**Comment by zengkid** [comment]
should not support target folder. you can put everything into resources folder.
