### ISSUE TITLE
Can we have a CHANGELOG.md ?

### ISSUE THREAD

**Issue by dedece35** [zengkid/SmartTomcat#65]
**Is your feature request related to a problem? Please describe.**
I think to have a CHANGELOG.md it's a good idea to verify what's new in neach new version

**Describe the solution you'd like**
create file CHANGELOG.md with the last known version.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by zengkid** [comment]
start from version [4.0.0]

**Comment by dedece35** [comment]
thank you @zengkid
