### ISSUE TITLE
Custom Context input not display - 3.8.3

### ISSUE THREAD

**Issue by cbeaujoin** [zengkid/SmartTomcat#66]
While editing configuration with revision 3.8.3 the Custom Context input is not displayed.

**Screenshots**
![unnamed](https://user-images.githubusercontent.com/35236/110818698-cad6b380-828d-11eb-842c-46d2ce8fd975.png)

**Intellij & SmartTomcat Version **
IntellijIDEA Ultimate 2020.2
SmartTomcat 3.8.3

**Comment by zengkid** [comment]
I didn't get your point.

**Comment by cbeaujoin** [comment]
![image](https://user-images.githubusercontent.com/35236/114396406-d4f61580-9b9d-11eb-842d-5664992c9e8c.png)

**Comment by zengkid** [comment]
@cbeaujoin the custom context file fix name as 'context_local.xml' in META-INF.

**Comment by yuezk** [comment]
@cbeaujoin You can put the custom context file under `META-INF` and name it as `context_local.xml`, the plugin will pick it automatically.

https://github.com/zengkid/SmartTomcat/blob/50ff6b2d692260c4ae24ef69dbf30c8002a47da8/src/main/java/com/poratu/idea/plugins/tomcat/conf/AppCommandLineState.java#L160-L165
