### ISSUE TITLE
Error running 'Test': The Module Root specified is not a module according to Intellij

### ISSUE THREAD

**Issue by Minabsapi** [zengkid/SmartTomcat#68]
When creating and running a new Smart Tomcat configuration (here named 'Test') IntelliJ shows the following error:

![image](https://user-images.githubusercontent.com/29603957/114212478-69b80380-9951-11eb-8d54-7c4ce0a209b8.png)

Here is the project structure (generated from a Maven archetype dedicated to Java EE 8)

```
├── buildAndRun.bat
├── buildAndRun.sh
├── Dockerfile
├── Java_EE_-_Crash_course.iml
├── pom.xml
├── README.md
├── server.xml
├── src
│   ├── main
│   │   ├── java
│   │   │   └── org
│   │   │       └── test
│   │   │           └── javaee
│   │   │               ├── JAXRSConfiguration.java
│   │   │               └── SampleResource.java
│   │   ├── resources
│   │   │   └── META-INF
│   │   │       ├── microprofile-config.properties
│   │   │       └── persistence.xml
│   │   └── webapp
│   │       └── WEB-INF
│   │           ├── beans.xml
│   │           └── ibm-web-ext.xml
│   └── test
│       └── java
│           └── org
│               └── test
│                   └── javaee
│                       └── SampleTest.java
└── target
    ├── classes
    │   ├── META-INF
    │   │   ├── microprofile-config.properties
    │   │   └── persistence.xml
    │   └── org
    │       └── test
    │           └── javaee
    │               ├── JAXRSConfiguration.class
    │               └── SampleResource.class
    ├── generated-sources
    │   └── annotations
    ├── generated-test-sources
    │   └── test-annotations
    └── test-classes
        └── org
            └── test
                └── javaee
                    └── SampleTest.class

29 directories, 19 files
```
**IntelliJ version**

IntelliJ IDEA 2021.1 (Community Edition)
Build #IC-211.6693.111, built on April 6, 2021
Runtime version: 11.0.10+9-b1341.35 amd64

**Smart Tomcat version**: 3.8.3

**Comment by zengkid** [comment]
Could you share project structs?

**Comment by Minabsapi** [comment]
Thanks for your attention. What do you mean by "project structs"? I already shared the structure, do you mean sending the files?

Just a note, I solved the problem first by providing a writable Apache Tomcat folder extracted from an archive (downloaded from the Apache website) to my project root.
But at the time of writing I got another problem, even doing this seems not to solve the issue anymore for another project. Might be linked to the [issue #55](https://github.com/zengkid/SmartTomcat/issues/55)

**Comment by Minabsapi** [comment]
Just solved the issue again with a step I forgot I did: providing an alternative path to the deployment directory. In my case I have two different paths for the same project due to a symlink. Full path didn't work and triggered the issue I reported, but providing the (shorter) path with the symlink works

Since it was definitely a problem on my end I think the issue should be closed

Before that I suggest to check if there would be something like a character limit to the deployment directory path — checked the plugin codebase a bit following the traceback, but I didn't look extensively, so I don't know if there's any limit, just a wild guess
