### ISSUE TITLE
Configuring CATALINA_BASE

### ISSUE THREAD

**Issue by jakobmaier** [zengkid/SmartTomcat#69]
**Describe the bug**
I have multiple tomcat instances on the same server to simulate different environments (DEV, TEST, QA, ...).
To select the correct tomcat-server, I usually configure CATALINA_BASE to point to the correct directory.

This is done by having multiple run configurations (one for each environment), and configuring the following _VM option_:

`-Dcatalina.base=D:/Path/to/my/alternative/catalineBase`

This works with the default Tomcat functionality in IntelliJ Ultimate, but not with SmartTomcat - the option is ignored.
The tomcat server starts, but no application is deployed.

**Intellij & SmartTomcat Version**

IntelliJ IDEA 2020.3.3 (Ultimate Edition)
Build #IU-203.7717.56, built on March 15, 2021
Runtime version: 11.0.10+8-b1145.96 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1981M
Cores: 8
Non-Bundled Plugins: CheckStyle-IDEA, com.dubreuia, com.poratu.idea.plugins.tomcat

SmartTomcat version: 3.8.3

**Comment by zengkid** [comment]
@jakobmaier I suggest you create multiple tomcat server and run/debug instance to support your requirement.

**Comment by yuezk** [comment]
Latest Smart Tomcat now supports overriding `catalina.base` via the VM option:

```
-Dcatalina.base=D:/Path/to/my/alternative/catalineBase
```

Closing it.
