### ISSUE TITLE
Error : Unable to find main class 3.8.4

### ISSUE THREAD

**Issue by kminhtri** [zengkid/SmartTomcat#70]
**Describe the bug**
Impossible to launch smart tomcat version 3.8.4 (works fine with 3.8.3) :
Here the error : "Error : Unable to find main class" when we launch the tomcat.
My Team and I are sad !

**Screenshots**
![2D5A4006-F3F6-4B7A-B9AC-79FCF4AFE53A](https://user-images.githubusercontent.com/2980358/115430295-892e1680-a204-11eb-9a4a-d9523b94e55b.png)

**Intellij & SmartTomcat Version (Help -> About copy & paste below)**
IntelliJ IDEA 2020.2.1 (Ultimate Edition)
Build #IU-202.6948.69, built on August 24, 2020
Runtime version: 11.0.8+10-b944.31 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 6077M
Cores: 8
Non-Bundled Plugins: GrepConsole, Lombook Plugin, com.poratu.idea.plugins.tomcat, org.ermadan.kafkalytic, mobi.hsz.idea.gitignore, org.sonarlint.idea

SmartTomcat version : 3.8.4

**Comment by azuldotdev** [comment]
Same problem using macOS version.

IntelliJ IDEA 2021.1 (Ultimate Edition)
Build #IU-211.6693.111, built on April 6, 2021
Runtime version: 11.0.10+9-b1341.35 aarch64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.2.3

**Comment by BSteffaniak** [comment]
Same problem. I was able to get it working by manually downloading version 3.8.3 from [here](https://plugins.jetbrains.com/plugin/9492-smart-tomcat/versions) and installing that version of the plugin "from disk". That seems to work for me until this version is fixed.

**Comment by yuezk** [comment]
Hi all, sorry for the trouble, I'm investigating this issue. For now, you can use @BSteffaniak 's comment as the workaround.

**Comment by yuezk** [comment]
Fixed in 3.8.5 through #71, pending approval from IntelliJ.

Reasoning: 3.8.4 intended fixing #63, it works well in my local environment because I have values in the `VM Options` field. But the code changes will break the users who don't have values in `VM Options`.

Thanks for your support.

**Comment by yuezk** [comment]
Closing it as it has been fixed in 3.8.5.
