### ISSUE TITLE
Displaying content of Localhost and Localhost_access log while running the App

### ISSUE THREAD

**Issue by mrafsyam** [zengkid/SmartTomcat#78]
**Is your feature request related to a problem? Please describe.**
Observing the content of the localhost log has been useful for me some times while troubleshooting. 
Not being able to view them, I had to deploy the App on local tomcat instead of running using the SmartTomcat.

**Describe the solution you'd like**
To be able to add the option to view the localhost and the localhost access file on a TAB next to console log

**Describe alternatives you've considered**
Deploy on local tomcat.

**Comment by tb12315** [comment]
你发的邮件我已经收到。会在近期内查看。

**Comment by zengkid** [comment]
easy to add in logs tab, access log should be in $user_home/.SmartTomcat/$project/$module/log 
![image](https://user-images.githubusercontent.com/55863385/170615462-a84e36e7-6302-4f8a-8cfd-70f2f2aec4c6.png)
