### ISSUE TITLE
日志文件自动重复添加

### ISSUE THREAD

**Issue by mynameisbob0905** [zengkid/SmartTomcat#81]
这里只配置了一个日志文件，但它会自动重复添加。

![image](https://user-images.githubusercontent.com/32627000/167603357-e56a08c0-f5f3-4c9f-8234-e9f74f83b849.png)

**Comment by zengkid** [comment]
the LogConfigurationPanel is from intellij product. have no idea to fix
 ``` java
group.addEditor(ExecutionBundle.message("logs.tab.title"), new LogConfigurationPanel<>());
```
