### ISSUE TITLE
Multiple Tomcat with 'AJP port 8009 already in use' issue

### ISSUE THREAD

**Issue by barats** [zengkid/SmartTomcat#9]
When I try to start two or more Tomcat via SmartTomcat plugin, it says AJP port 8009 already in use and failed. 

Could you update your plugin and modify AJP port number when there are multiple tomcat instance running ? 

Many thanks ahead.

**Comment by barats** [comment]
What if I want to start multiple instances from single Tomcat ? 

I checked out your code and can't help but thinking: maybe we can do some alternations in `com.poratu.idea.plugins.tomcat.conf.AppCommandLineState` to support such a mechanism. 

What's your opinion about this approach ?

**Comment by yl-coder** [comment]
@barats you can do that by modifying the server.xml of each run configuration. Basically the server.xml of each run configuration you setup can be found at $USERHOME/.smartTomcat/configurationName/conf/server.xml. 

If you want a automatic way, you can build a custom jar from my forked repo. [link](https://github.com/yl-coder/SmartTomcat/tree/testing-ajp-shutdown-port)

It will automatically assign AJP and tomcat port to be HTTP port + 1/ + 2. 

I will create the GUI for users to key in those port in future and create a pull request. when i'm free.
