### ISSUE TITLE
bug in update 4.3.4

### ISSUE THREAD

**Issue by almacen2015** [zengkid/SmartTomcat#91]
When updating and launching a project with the plugin, a .SmartTomcat error will appear where it indicates a folder within the webapp with the same project name that did not exist

**Comment by yuezk** [comment]
Hi @almacen2015 is there any error detailed message or screenshot?

**Comment by almacen2015** [comment]
I forgot to take a screenshot, but the error sent me to the .smartTomcat folder towards my project name and then located in a folder within the webapp that did not exist, so I had to go back to version 4.3.3

**Comment by yuezk** [comment]
It works well for me, would you mind update to 4.3.4 to catch the error message or screenshot? Thanks.

**Comment by yuezk** [comment]
That’s it. Looks like the Context element was added by Eclipse, I guess you have ever used Eclipse. If you like, you can just delete the `Context` element and it will work with 4.3.4.

Anyway, I will update the code to deal with this situation in the next release.

**Comment by yuezk** [comment]
Fixed in 4.3.5
