### ISSUE TITLE
Tomcat is launched instead running a test from the context menu

### ISSUE THREAD

**Issue by setuper** [zengkid/SmartTomcat#92]
In the latest version of the plugin (4.3.5), Tomcat is launched instead running a test from the context menu.

![screen](https://user-images.githubusercontent.com/3885792/190976232-3baf0a9a-2eb3-4221-8e8c-a7ca8a7091ac.jpg)

IntelliJ IDEA 2022.2.2 (Community Edition)
Build #IC-222.4167.29, built on September 13, 2022
Runtime version: 17.0.4+7-b469.53 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 4096M
Cores: 16
Registry:
    debugger.watches.in.variables=false

Non-Bundled Plugins:
    com.poratu.idea.plugins.tomcat (4.3.5)

Kotlin: 222-1.7.10-release-334-IJ4167.29

**Comment by yuezk** [comment]
Ah, I see. Looks like I need to restrict the check condition for webroot.

**Comment by yuezk** [comment]
@setuper I couldn't reproduce it locally. Can you provide the minimal reproducible project? Thanks.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/3297602/191166109-5a4638ae-2e00-4643-a713-25bf22ecb18d.png">

**Comment by setuper** [comment]
You must have the folder: web/WEB-INF

![screen](https://user-images.githubusercontent.com/3885792/191479451-7d6ba0b7-7b0d-49f9-afde-7d40af77f386.jpg)
