### ISSUE TITLE
How does plugin know project's build folder

### ISSUE THREAD

**Issue by efcjunior** [zengkid/SmartTomcat#96]
I am trying to figure out how the Smart Tomcat plugin knows that the compiled files are generated in the build directory, even leaving the default deployment directory like "/src/main/webapp".The folder "classes" is not in the WEB-INF directory. The build task process of the Gradle tool generates it in the build directory.

At which moment does the Smart Tomcat plugin override the default deployment directory?

Thanks.

**Comment by yuezk** [comment]
Actually, Smart Tomcat is not "smart" enough to detect your deployment directory. 😅

It only interacts with the plugin APIs provided by IntelliJ IDEA, it has no idea what the default deployment directory is used by Gradle. And I didn't find a reliable way to find the deployment directory by leveraging the plugin APIs.

So, under the hood, it will iterate the project file index to find the folder that contains the `WEB-INF` folder. If it finds multiple folders, it will just choose the first one.

If the auto-filled deployment directory isn't correct, feel free to change it to the correct one manually.

**Comment by efcjunior** [comment]
I noticed when I run the Smart Tomcat first time this folder structure is created `/home/devcunha/.SmartTomcat/name_project/project_name.main/conf/Catalina/localhost` and there is a file in this folder called `project_name.xml` that shows where  folder build is

`    <PreResources base="/home/devcunha/dev/projects/project_name/oficial/project_name/build/classes/main" className="org.apache.catalina.webresources.DirResourceSet" webAppMount="/WEB-INF/classes"/>
`

If I understood your explanation, Smart Plugin extracts this build path through plugin APIs. Right?

**Comment by yuezk** [comment]
Yes, these `<PreResources>` items are collected through the plugin API.

**Comment by efcjunior** [comment]
Perfect. Thank you for the clarifications.

**Comment by yuezk** [comment]
If you interested, the related code is https://github.com/zengkid/SmartTomcat/blob/f71d3ca9dd7c9894ce10e98bed2142f32b70f604/src/main/java/com/poratu/idea/plugins/tomcat/conf/TomcatCommandLineState.java#L247

**Comment by efcjunior** [comment]
Excellent. I was looking for this code. Thank you so much!
