### ISSUE TITLE
java.lang.IllegalStateException: Unable to complete the scan for annotations for web application [/ggas] due to a StackOverflowError

### ISSUE THREAD

**Issue by efcjunior** [zengkid/SmartTomcat#97]
- When I execute Smart Tomcat after building the Gradle task this error occurs: `org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/ggas]]`
- I've noticed when I'm debugging the Smart Tomcat plugin and I do a breakpoint in the `TomcatCommandLineState class `and wait for milliseconds, this error doesn't happen. 
- I'm trying to figure out if this error happens because the Tomcat starts before the Smart Tomcat Plugin finishes its configuration.

**Screenshots**
![image](https://user-images.githubusercontent.com/2645720/195616075-b2331b79-1845-479e-98d2-af5ef82206f1.png)

**Intellij & SmartTomcat Version (Help -> About copy & paste below)**
IntelliJ IDEA 2022.2.3 (Community Edition)

**Comment by yuezk** [comment]
From Googling, looks like you have a cyclic dependency. Does https://stackoverflow.com/questions/17584495/unable-to-complete-the-scan-for-annotations-for-web-application-app-due-to-a helpful?

**Comment by efcjunior** [comment]
You are right. I've found more than one dependency with the same name. 

![Screenshot from 2022-10-14 08-29-58](https://user-images.githubusercontent.com/2645720/195836851-ce7cccb9-184b-4801-9b26-3fa28accaa6c.png)

I removed one and this error hasn't occurred.

Thank you again.
